name: Build/release

on: push
# on: 
#  push:
#    tags:
#      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: npm ci
      - run: npm run build 
      - run: npm run zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/distribute/installers/*.zip
